// Flood the DB with realistic demo data:
//   - 25 fake verified users (+ keeps your real account)
//   - 3 fully-played past seasons (2022, 2023, 2024) with final ranks
//   - 1 active season (2025) at Week 5: real ESPN games wk1-5, everyone graded
//     through wk4, and everyone has a pending Week 5 pick already submitted
//
// Picks for past/current weeks are generated by actually picking the REAL ESPN
// winner most of the time (so most survive) with a sprinkle of upsets (so people
// get eliminated and the losers bracket / eliminated list populate). Grading for
// past weeks is applied with the same rules the app uses (win=survive,
// loss/tie/missed=loss, main->losers->eliminated).
//
// NO EMAILS are sent — this script writes directly to the DB and never invokes
// the Netlify functions.
//
//   node scripts/flood-seed.mjs

import { readFileSync } from "node:fs";
import { neon } from "@neondatabase/serverless";
import { randomUUID } from "node:crypto";

try {
  const envFile = readFileSync(new URL("../.env.local", import.meta.url), "utf8");
  for (const line of envFile.split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
} catch {}

const url = process.env.DATABASE_URL || process.env.NETLIFY_DATABASE_URL;
if (!url) { console.error("Missing DATABASE_URL"); process.exit(1); }
const sql = neon(url);

// --- deterministic PRNG so reruns are stable -------------------------------
let _s = 12345;
function rng() { _s = (_s * 1103515245 + 12345) & 0x7fffffff; return _s / 0x7fffffff; }
function pick(arr) { return arr[Math.floor(rng() * arr.length)]; }

const FIRST = ["Mike","Sarah","Jess","Tom","Dave","Kate","Nick","Liz","Sam","Joe","Amy","Ben","Chris","Dana","Eric","Faith","Greg","Hana","Ian","Jen","Kyle","Lena","Matt","Nina","Omar"];
const LAST = ["Olah","Reed","Cole","Vega","Shaw","Diaz","Knox","Webb","Frye","Hale","Lund","Park","Ross","Tate","Wolf","Bui","Cruz","Dunn","Egan","Ford"];

const ESPN = (year, week) =>
  `https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?dates=${year}&seasontype=2&week=${week}`;

async function fetchWeek(year, week) {
  const res = await fetch(ESPN(year, week));
  const json = await res.json();
  return (json.events ?? []).map((ev) => {
    const c = ev.competitions[0];
    const home = c.competitors.find((x) => x.homeAway === "home");
    const away = c.competitors.find((x) => x.homeAway === "away");
    const hs = home.score != null ? Number(home.score) : null;
    const as = away.score != null ? Number(away.score) : null;
    const completed = !!c.status?.type?.completed;
    let winner = null;
    if (completed && hs != null && as != null && hs !== as)
      winner = hs > as ? home.team.abbreviation : away.team.abbreviation;
    return {
      id: ev.id, week, date: ev.date,
      home: home.team.abbreviation, away: away.team.abbreviation,
      homeName: home.team.displayName, awayName: away.team.displayName,
      hs, as, completed, winner,
      status: c.status.type.name,
      spread: c.odds?.[0]?.details ?? null,
      ou: c.odds?.[0]?.overUnder != null ? String(c.odds[0].overUnder) : null,
    };
  });
}

async function insertSeason({ year, status, phase, currentWeek, lockAt }) {
  const id = randomUUID();
  await sql`insert into seasons (id, year, status, phase, current_week, lock_at, buy_in, venmo_handle)
            values (${id}, ${year}, ${status}, ${phase}, ${currentWeek}, ${lockAt}, '50', '@jim-olah')
            on conflict (year) do update set status=excluded.status, current_week=excluded.current_week,
              lock_at=excluded.lock_at returning id`;
  const row = (await sql`select id from seasons where year=${year}`)[0];
  return row.id;
}

async function insertGames(seasonId, games) {
  for (const g of games) {
    await sql`insert into games (id, season_id, week, seasontype, home_abbr, away_abbr,
        home_name, away_name, kickoff, status, completed, home_score, away_score,
        winner_abbr, spread_detail, over_under)
      values (${g.id}, ${seasonId}, ${g.week}, 2, ${g.home}, ${g.away}, ${g.homeName},
        ${g.awayName}, ${g.date}, ${g.status}, ${g.completed}, ${g.hs}, ${g.as},
        ${g.winner}, ${g.spread}, ${g.ou})
      on conflict (season_id, id) do nothing`;
  }
}

// Simulate one entry through `weeks` of a season using real winners.
// upsetRate = chance the player picks a loser on a given week.
// Returns { bracket, eliminatedWeek, picks: [{week, team, bracket, result}] }
function simulateEntry(gamesByWeek, weeks, upsetRate) {
  let bracket = "main";
  let eliminatedWeek = null;
  const usage = { main: {}, losers: {} };
  const picks = [];
  for (let w = 1; w <= weeks; w++) {
    if (bracket === "eliminated") break;
    const games = gamesByWeek[w] || [];
    if (games.length === 0) continue;
    // candidate teams not yet used twice in current bracket
    const cands = [];
    for (const g of games) {
      for (const [team, opp] of [[g.winner, null], [g.home, 0], [g.away, 0]]) {}
    }
    // Build team->won map
    const teamWon = {};
    const teamsThisWeek = [];
    for (const g of games) {
      teamsThisWeek.push(g.home, g.away);
      teamWon[g.home] = g.winner === g.home;
      teamWon[g.away] = g.winner === g.away;
    }
    const usable = teamsThisWeek.filter((t) => (usage[bracket][t] || 0) < 2);
    const winners = usable.filter((t) => teamWon[t]);
    const losers = usable.filter((t) => !teamWon[t]);
    let team;
    if (rng() < upsetRate && losers.length) team = pick(losers);
    else if (winners.length) team = pick(winners);
    else team = pick(usable.length ? usable : teamsThisWeek);
    usage[bracket][team] = (usage[bracket][team] || 0) + 1;
    const won = teamWon[team];
    const result = won ? "win" : "loss";
    picks.push({ week: w, team, bracket, result });
    if (!won) {
      if (bracket === "main") { bracket = "losers"; eliminatedWeek = eliminatedWeek ?? w; usage.losers = {}; }
      else { bracket = "eliminated"; eliminatedWeek = eliminatedWeek ?? w; }
    }
  }
  return { bracket, eliminatedWeek, picks };
}

async function makeUser(name, isAdmin = false) {
  const id = randomUUID();
  const email = name.toLowerCase().replace(/[^a-z]/g, ".") + "@example.com";
  await sql`insert into "user" (id, name, email, email_verified, display_name, is_admin)
            values (${id}, ${name}, ${email}, true, ${name}, ${isAdmin})
            on conflict (email) do nothing`;
  return (await sql`select id from "user" where email=${email}`)[0].id;
}

async function addEntry(seasonId, userId, sim, weeks, completeSeason) {
  const id = randomUUID();
  await sql`insert into entries (id, season_id, user_id, bracket, paid, paid_marked_by_user, eliminated_week)
            values (${id}, ${seasonId}, ${userId}, ${sim.bracket}, true, true, ${sim.eliminatedWeek})
            on conflict (season_id, user_id) do nothing`;
  const entryId = (await sql`select id from entries where season_id=${seasonId} and user_id=${userId}`)[0].id;
  for (const p of sim.picks) {
    await sql`insert into picks (id, entry_id, season_id, week, team_abbr, bracket, result)
              values (${randomUUID()}, ${entryId}, ${seasonId}, ${p.week}, ${p.team}, ${p.bracket}, ${p.result})
              on conflict (entry_id, week) do nothing`;
  }
  return entryId;
}

async function main() {
  console.log("Flood-seeding…");

  // Users: 25 fake + keep your real one.
  const names = [];
  for (let i = 0; i < 25; i++) names.push(`${FIRST[i]} ${pick(LAST)}`);
  const userIds = [];
  for (const n of names) userIds.push(await makeUser(n));
  const me = (await sql`select id from "user" where email='harry.schlechter391@gmail.com'`)[0];
  if (me) userIds.push(me.id);
  console.log(`  ${userIds.length} users.`);

  // 3 past, fully-played seasons (archived) + current 2025 active at wk5.
  const PAST = [2022, 2023, 2024];
  for (const year of PAST) {
    const gw = {};
    for (let w = 1; w <= 18; w++) gw[w] = await fetchWeek(year, w);
    const seasonId = await insertSeason({ year, status: "archived", phase: "regular", currentWeek: 18, lockAt: null });
    for (let w = 1; w <= 18; w++) await insertGames(seasonId, gw[w]);
    // Simulate every user through the full season.
    const results = [];
    for (const uid of userIds) {
      const sim = simulateEntry(gw, 18, 0.18 + rng() * 0.12);
      const entryId = await addEntry(seasonId, uid, sim, 18, true);
      results.push({ uid, entryId, sim });
    }
    // Rank: alive-longest first (later eliminatedWeek = better; null = survived).
    results.sort((a, b) => (b.sim.eliminatedWeek ?? 99) - (a.sim.eliminatedWeek ?? 99));
    for (let i = 0; i < results.length; i++) {
      await sql`update entries set final_rank=${i + 1} where id=${results[i].entryId}`;
    }
    console.log(`  ${year}: archived, ${results.length} entries, ranked.`);
  }

  // Current season 2025, active, Week 5.
  const gw = {};
  for (let w = 1; w <= 5; w++) gw[w] = await fetchWeek(2025, w);
  // lock in 2h so Week 5 picks are still "open"/pre-result in the UI sense.
  const lock = new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString();
  const seasonId = await insertSeason({ year: 2025, status: "active", phase: "regular", currentWeek: 5, lockAt: lock });
  for (let w = 1; w <= 5; w++) await insertGames(seasonId, gw[w]);

  // Everyone plays weeks 1-4 (graded), then has a PENDING week-5 pick.
  for (const uid of userIds) {
    const sim = simulateEntry(gw, 4, 0.16 + rng() * 0.12); // weeks 1-4 graded
    const entryId = await addEntry(seasonId, uid, sim, 4, false);
    // Week 5 pending pick for everyone still alive.
    if (sim.bracket !== "eliminated") {
      const pickBracket = sim.bracket; // main or losers
      const games = gw[5] || [];
      const used = {};
      for (const p of sim.picks) if (p.bracket === pickBracket) used[p.team] = (used[p.team] || 0) + 1;
      const teams = games.flatMap((g) => [g.home, g.away]).filter((t) => (used[t] || 0) < 2);
      const team = pick(teams.length ? teams : games.flatMap((g) => [g.home, g.away]));
      await sql`insert into picks (id, entry_id, season_id, week, team_abbr, bracket, result)
                values (${randomUUID()}, ${entryId}, ${seasonId}, 5, ${team}, ${pickBracket}, 'pending')
                on conflict (entry_id, week) do nothing`;
    }
  }

  const counts = await sql`select bracket, count(*)::int n from entries where season_id=${seasonId} group by bracket`;
  const picked = await sql`select count(*)::int n from picks where season_id=${seasonId} and week=5`;
  console.log(`  2025: active wk5. Brackets: ${JSON.stringify(counts)}. Week-5 picks in: ${picked[0].n}.`);
  console.log("\nDone. Open http://localhost:3000 — you're in the 2025 season at Week 5.");
}

main().catch((e) => { console.error(e); process.exit(1); });
